### ISSUE TITLE
support methods

### ISSUE THREAD

**Issue by nikomatsakis** [lark-exploration/lark#178]
We had talked about supporting a simple form of methods like this:

```
struct Foo {
    def bar() {
    }
}
```

(Or did we not want to have the `def` keyword? I forget.)

Making this change requires a few things:

- First, extend the parser and "connect" the methods  in the entity system
- The type-checker will *hopefully* just work, but it may need some debugging
- Extend the repl etc

### Extending the parser

Struct declarations are parsed in this code:

https://github.com/lark-exploration/lark/blob/a4aaa3ad540f5d6d4c013d60fe13e55d3063c208/components/lark-parser/src/macros/struct_declaration.rs#L31-L37

To support methods, we want to add something similar to this line (which parses the set of fields):

https://github.com/lark-exploration/lark/blob/a4aaa3ad540f5d6d4c013d60fe13e55d3063c208/components/lark-parser/src/macros/struct_declaration.rs#L55-L58

This is the "syntax definition" for a field:

https://github.com/lark-exploration/lark/blob/a4aaa3ad540f5d6d4c013d60fe13e55d3063c208/components/lark-parser/src/syntax/field.rs#L26-L27

We might want to add something like that for a method or function. (This may want to share code with [the code in `function_declaration.rs`](https://github.com/lark-exploration/lark/blob/master/components/lark-parser/src/macros/function_declaration.rs#L46), which parses functions.)

### Entity tree

The entity tree is represented by the `ParsedFoo` types, which implement the entity trait. For example, a parsed struct is represented by this struct:

https://github.com/lark-exploration/lark/blob/a4aaa3ad540f5d6d4c013d60fe13e55d3063c208/components/lark-parser/src/macros/struct_declaration.rs#L80-L82

and in particular this method (`parse_children`) has the job of returning the list of subentities:

https://github.com/lark-exploration/lark/blob/a4aaa3ad540f5d6d4c013d60fe13e55d3063c208/components/lark-parser/src/macros/struct_declaration.rs#L85-L89

(The name "parse" is because we are *meant* to (possibly) be parsing subentities and things lazilly, but right now it's all eager.)

The entities in these cases are `ParsedField` instances:

https://github.com/lark-exploration/lark/blob/a4aaa3ad540f5d6d4c013d60fe13e55d3063c208/components/lark-parser/src/syntax/field.rs#L29-L34

which implement `LazyParsedEntity` here:

https://github.com/lark-exploration/lark/blob/a4aaa3ad540f5d6d4c013d60fe13e55d3063c208/components/lark-parser/src/syntax/field.rs#L59

so presumably if we add a `ParsedMethod` it too would implement that trait and be incorporated into the "subentity list" in much the same way.

I think if we do this, things will actually "just work" in type-checking -- the type-checker uses [the `members` query](https://github.com/lark-exploration/lark/blob/a4aaa3ad540f5d6d4c013d60fe13e55d3063c208/components/lark-parser/src/query_definitions.rs#L216-L219) to look up methods, and *that* in turn draws from the `child_entities` query.

**Comment by jonathandturner** [comment]
Fixed by #179
